name: Linux CI

on:
  push:
    branches: [ main, master ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    steps:
      # ───────────────────────────────────────────────────────────────────
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      # ───────────────────────────────────────────────────────────────────
      - name: Install ${{ matrix.compiler }}
        run: |
          set -euo pipefail
          sudo apt-get update
          if [[ "${{ matrix.compiler }}" == "clang" ]]; then
            sudo apt-get install -y clang ccache
          else
            sudo apt-get install -y build-essential ccache   # gcc / g++
          fi
      # ───────────────────────────────────────────────────────────────────
      - name: List C sources (debug aid)
        run: |
          set -euo pipefail
          echo "C files found under Split_kMeans/:"
          find Split_kMeans -maxdepth 1 -name '*.c' -print
      # ───────────────────────────────────────────────────────────────────
      - name: Build (via Makefile)
        run: |
          cd Split_kMeans
          make CC=${{ matrix.compiler }}
      # ───────────────────────────────────────────────────────────────────
      - name: Prepare mini dataset (with fallback)
        run: |
          set -euo pipefail
          mkdir -p data gt centroids
          if [ -d ci-fixtures/data ] && [ -d ci-fixtures/gt ] && [ -d ci-fixtures/centroids ]; then
            echo "Using provided fixtures..."
            cp -R ci-fixtures/data/*       ./data/ || true
            cp -R ci-fixtures/gt/*         ./gt/   || true
            cp -R ci-fixtures/centroids/*  ./centroids/ || true
          else
            echo "No fixtures found — creating dummy data."
            echo "1.0 2.0"   > data/sample.txt
            echo "1"        > gt/sample.txt
            echo "1.0 2.0"  > centroids/sample.txt
          fi
      # ───────────────────────────────────────────────────────────────────
      - name: Smoke-test binary
        run: |
          set -euo pipefail
          command -v timeout >/dev/null || sudo apt-get install -y coreutils
          timeout 10s ./Split_kMeans/split_kmeans || (echo "program exited with non-zero status"; exit 1)

      - name: Upload binary (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: split_kmeans-${{ matrix.compiler }}
          path: Split_kMeans/split_kMeans
          if-no-files-found: warn