name: Linux CI (bare minimum)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install gcc
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build
        run: |
          set -e
          cd Split_kMeans
          gcc --version
          SRC_FILES=$(ls *.c)
          gcc -std=c11 -O2 -pthread $SRC_FILES -o ../clustering -lm

      - name: Quick start check
        env:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8
        run: |
          set -e
          file ./clustering            # confirm it's a Linux ELF binary
          ldd ./clustering || true     # show dynamic deps (don't fail CI)
          # Prefer a non-interactive flag if you have one:
          ./clustering --help >/dev/null 2>&1 || \
          timeout 5s ./clustering >/dev/null 2>&1 || \
          (echo "binary built but no quick-run option; consider providing --help"; exit 0)
